In [56]:
%load_ext autoreload
%autoreload 2
from today_market import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [41]:

sub = get_today()
sub

read cached daily/2025-04-14.pq

,code,name,ratio,turnover,amount,vr,price,p_price,high,low,open,changed,dpe,volume,cap,traded_cap,market,date
0,873132,泰鹏智能,29.99,51.68,3.087520e+08,2.89,22.41,17.24,22.41,17.40,18.50,5.17,60.79,145351,1856085840,630241472,深A,2025-04-14
1,301392,汇成真空,20.00,10.90,2.645072e+08,1.15,114.29,95.24,114.29,96.78,96.78,19.05,132.92,24533,11429000000,2571525000,深A,2025-04-14
2,301209,联合化学,20.00,20.53,2.221961e+08,1.57,48.29,40.24,48.29,40.00,40.15,8.05,65.73,50287,3863200000,1183105000,深A,2025-04-14
3,300963,中洲特材,20.00,21.25,6.376126e+08,0.75,15.84,13.20,15.84,13.28,13.33,2.64,53.46,426130,5189184000,3176426769,深A,2025-04-14
4,301287,康力源,20.00,32.23,1.899987e+08,3.76,35.40,29.50,35.40,30.51,30.95,5.90,41.34,54896,2360118000,602909790,深A,2025-04-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5388,002286,保龄宝,-7.37,17.73,5.306266e+08,2.40,8.04,8.68,8.40,7.90,8.40,-0.64,22.06,655199,2972929735,2971511881,深A,2025-04-14
5389,688287,ST观典,-9.24,4.46,7.024847e+07,5.19,4.32,4.76,4.45,4.06,4.45,-0.44,-15.99,165080,1600627392,1600627392,沪A,2025-04-14
5390,002800,天顺股份,-9.97,25.02,4.791332e+08,1.63,13.28,14.75,14.26,13.28,13.28,-1.47,83.80,354451,2021920730,1881166448,深A,2025-04-14
5391,002133,广宇集团,-10.09,18.07,4.033739e+08,3.03,2.85,3.17,3.09,2.85,3.01,-0.32,-10.88,1391506,2206310899,2194130073,深A,2025-04-14
5392,301665,C泰禾,-11.24,60.78,7.684828e+08,0.73,35.55,40.05,37.33,33.88,35.36,-4.50,61.23,218246,15997500000,1276468574,深A,2025-04-14

In [42]:
df = ef.stock.get_daily_billboard()
df

,股票代码,股票名称,上榜日期,解读,收盘价,涨跌幅,换手率,龙虎榜净买额,龙虎榜买入额,龙虎榜卖出额,龙虎榜成交额,市场总成交额,净买额占总成交比,成交额占总成交比,流通市值,上榜原因
0,000062,深圳华强,2025-04-14,1家机构买入，成功率50.99%,25.51,10.0043,9.3486,28330251.12,2.085330e+08,1.802027e+08,3.887357e+08,2392585168,1.184085,16.247516,2.665614e+10,日涨幅偏离值达到7%的前5只证券
1,000510,新金路,2025-04-14,普通席位买入，成功率52.69%,4.63,9.9762,2.4783,1281195.12,7.401625e+07,7.273506e+07,1.467513e+08,347766545,0.368407,42.198225,2.808858e+09,连续三个交易日内，涨幅偏离值累计达到20%的证券
2,000566,海南海药,2025-04-14,1家机构买入，成功率44.92%,5.00,5.7082,12.4799,30657076.24,9.965634e+07,6.899926e+07,1.686556e+08,729423937,4.202916,23.121753,5.829549e+09,日振幅值达到15%的前5只证券
3,000759,中百集团,2025-04-14,1家机构买入，成功率38.14%,9.69,4.1935,37.0077,53377600.74,2.485843e+08,1.952067e+08,4.437911e+08,2365018707,2.256963,18.764802,6.353791e+09,日换手率达到20%的前5只证券
4,001212,中旗新材,2025-04-14,1家机构买入，成功率35.77%,55.29,10.0080,32.5515,-43006624.02,2.496632e+08,2.926699e+08,5.423331e+08,1850869019,-2.323591,29.301538,5.970982e+09,日涨幅偏离值达到7%的前5只证券
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,839371,欧福蛋业,2025-04-14,主力做T，成功率15.94%,13.50,1.0479,34.9990,-1376952.20,2.483743e+07,2.621438e+07,5.105182e+07,280789100,-0.490387,18.181552,7.892797e+08,当日换手率达到20%的前5只股票
69,872351,华光源海,2025-04-14,西藏自治区资金卖出，成功率37.88%,27.95,-5.2542,53.4049,-8736789.30,3.843706e+07,4.717385e+07,8.561091e+07,536725500,-1.627795,15.950595,9.855293e+08,当日换手率达到20%的前5只股票
70,873132,泰鹏智能,2025-04-14,买一主买，成功率29.40%,22.41,29.9884,51.6836,-58862290.21,4.126802e+07,1.001303e+08,1.413983e+08,308752000,-19.064586,45.796731,6.302415e+08,当日换手率达到20%的前5只股票
71,873132,泰鹏智能,2025-04-14,西藏自治区资金买入，成功率28.20%,22.41,29.9884,51.6836,-60777560.39,5.941791e+07,1.201955e+08,1.796134e+08,589441800,-10.311037,30.471775,6.302415e+08,北交所股票最近3个有成交的交易日以内收盘价涨跌幅偏离值累计达到+40%(-40%)
72,873132,泰鹏智能,2025-04-14,买一主买，成功率29.40%,22.41,29.9884,51.6836,-58862290.21,4.126802e+07,1.001303e+08,1.413983e+08,308752000,-19.064586,45.796731,6.302415e+08,当日收盘价涨幅达到20%的前5只股票

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   股票代码      73 non-null     object
 1   股票名称      73 non-null     object
 2   上榜日期      73 non-null     object
 3   解读        73 non-null     object
 4   收盘价       73 non-null     float64
 5   涨跌幅       73 non-null     float64
 6   换手率       73 non-null     float64
 7   龙虎榜净买额    73 non-null     float64
 8   龙虎榜买入额    73 non-null     float64
 9   龙虎榜卖出额    73 non-null     float64
 10  龙虎榜成交额    73 non-null     float64
 11  市场总成交额    73 non-null     int64
 12  净买额占总成交比  73 non-null     float64
 13  成交额占总成交比  73 non-null     float64
 14  流通市值      73 non-null     float64
 15  上榜原因      73 non-null     object
dtypes: float64(10), int64(1), object(5)
memory usage: 9.2+ KB

In [44]:
one = ef.stock.get_quote_history('601086')
one

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,国芳集团,601086,2017-09-29,2.39,3.15,3.15,2.39,493,221954.0,43.18,78.98,1.39,0.03
1,国芳集团,601086,2017-10-09,3.61,3.61,3.61,3.61,349,174839.0,0.00,14.60,0.46,0.02
2,国芳集团,601086,2017-10-10,4.11,4.11,4.11,4.11,196,107996.0,0.00,13.85,0.50,0.01
3,国芳集团,601086,2017-10-11,4.66,4.66,4.66,4.66,217,131502.0,0.00,13.38,0.55,0.01
4,国芳集团,601086,2017-10-12,5.27,5.27,5.27,5.27,682,455174.0,0.00,13.09,0.61,0.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,国芳集团,601086,2025-04-08,6.34,6.34,6.34,6.34,65748,41684232.0,0.00,10.07,0.58,0.99
1822,国芳集团,601086,2025-04-09,6.97,6.97,6.97,6.97,52318,36465646.0,0.00,9.94,0.63,0.79
1823,国芳集团,601086,2025-04-10,7.67,7.67,7.67,7.67,246827,189316041.0,0.00,10.04,0.70,3.71
1824,国芳集团,601086,2025-04-11,8.44,8.44,8.44,8.44,81569,68844236.0,0.00,10.04,0.77,1.22
1825,国芳集团,601086,2025-04-14,8.44,9.28,9.28,8.21,573878,515968665.0,12.68,9.95,0.84,8.62

In [46]:
one.columns = ['name', 'code','date', 'open', 'close','high', 'low', 'volume', 'amount', 'amplitude','ratio', 'changed', 'turnover']
one

,name,code,date,open,close,high,low,volume,amount,amplitude,ratio,changed,turnover
0,国芳集团,601086,2017-09-29,2.39,3.15,3.15,2.39,493,221954.0,43.18,78.98,1.39,0.03
1,国芳集团,601086,2017-10-09,3.61,3.61,3.61,3.61,349,174839.0,0.00,14.60,0.46,0.02
2,国芳集团,601086,2017-10-10,4.11,4.11,4.11,4.11,196,107996.0,0.00,13.85,0.50,0.01
3,国芳集团,601086,2017-10-11,4.66,4.66,4.66,4.66,217,131502.0,0.00,13.38,0.55,0.01
4,国芳集团,601086,2017-10-12,5.27,5.27,5.27,5.27,682,455174.0,0.00,13.09,0.61,0.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,国芳集团,601086,2025-04-08,6.34,6.34,6.34,6.34,65748,41684232.0,0.00,10.07,0.58,0.99
1822,国芳集团,601086,2025-04-09,6.97,6.97,6.97,6.97,52318,36465646.0,0.00,9.94,0.63,0.79
1823,国芳集团,601086,2025-04-10,7.67,7.67,7.67,7.67,246827,189316041.0,0.00,10.04,0.70,3.71
1824,国芳集团,601086,2025-04-11,8.44,8.44,8.44,8.44,81569,68844236.0,0.00,10.04,0.77,1.22
1825,国芳集团,601086,2025-04-14,8.44,9.28,9.28,8.21,573878,515968665.0,12.68,9.95,0.84,8.62

In [54]:
sub.query("traded_cap > 1e10 and amount > 3e8")

,code,name,ratio,turnover,amount,vr,price,p_price,high,low,open,changed,dpe,volume,cap,traded_cap,market,date
10,300723,一品红,19.30,6.89,1.154680e+09,1.63,41.97,35.18,42.22,35.33,36.00,6.79,-57.67,291175,18957545389,17745710030,深A,2025-04-14
27,832982,锦波生物,11.50,3.67,6.123168e+08,1.21,378.00,339.01,378.00,333.33,338.99,38.99,34.21,16836,33457460400,17346828240,深A,2025-04-14
62,002675,东诚药业,10.03,3.06,3.208230e+08,2.29,14.26,12.96,14.26,13.09,13.15,1.30,63.97,227230,11758734753,10600655754,深A,2025-04-14
67,002487,大金重工,10.02,2.52,3.969683e+08,1.42,25.04,22.76,25.04,24.60,24.60,2.28,33.70,158842,15969243699,15798243461,深A,2025-04-14
69,601020,华钰矿业,10.02,7.21,1.131543e+09,0.72,19.76,17.96,19.76,18.09,18.09,1.80,79.44,591418,16202502432,16202502432,沪A,2025-04-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5360,002028,思源电气,-3.89,1.89,8.267624e+08,1.46,71.60,74.50,74.75,70.76,74.68,-2.90,26.64,114532,55582844364,43297961881,深A,2025-04-14
5365,300627,华测导航,-4.17,2.03,3.740978e+08,0.96,39.80,41.53,41.77,39.75,41.51,-1.73,38.09,92369,21868614425,18079541194,深A,2025-04-14
5367,688385,复旦微电,-4.20,2.87,7.826027e+08,0.91,50.16,52.36,52.39,50.02,52.09,-2.20,71.96,154089,41202793368,26940800568,沪A,2025-04-14
5368,002653,海思科,-4.28,1.59,3.880939e+08,1.20,45.42,47.45,46.99,44.60,46.75,-2.03,128.63,85403,50866674197,24337264974,深A,2025-04-14
5381,603129,春风动力,-5.46,2.83,6.660200e+08,1.18,151.45,160.20,160.20,150.60,160.03,-8.75,16.03,43125,23107887061,23107887061,沪A,2025-04-14

In [57]:
o2 = get_one('688388')
o2

,name,code,date,open,close,high,low,volume,amount,amplitude,ratio,changed,turnover
0,嘉元科技,688388,2019-07-22,45.75,39.07,52.17,23.72,402094,2.111280e+09,151.41,107.93,20.28,76.10
1,嘉元科技,688388,2019-07-23,32.17,35.01,37.85,31.46,165822,8.515070e+08,16.36,-10.39,-4.06,31.38
2,嘉元科技,688388,2019-07-24,35.46,38.29,38.58,35.46,179648,9.758346e+08,8.91,9.37,3.28,34.00
3,嘉元科技,688388,2019-07-25,39.20,40.73,43.10,39.19,201243,1.197895e+09,10.21,6.37,2.44,38.09
4,嘉元科技,688388,2019-07-26,41.10,39.80,44.23,39.73,198737,1.216335e+09,11.05,-2.28,-0.93,37.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,嘉元科技,688388,2025-04-08,15.00,15.48,16.24,15.00,111292,1.729183e+08,7.91,-1.28,-0.20,2.61
1385,嘉元科技,688388,2025-04-09,15.30,15.62,15.81,13.50,128757,1.893228e+08,14.92,0.90,0.14,3.02
1386,嘉元科技,688388,2025-04-10,16.48,16.13,17.04,16.08,108232,1.794541e+08,6.15,3.27,0.51,2.54
1387,嘉元科技,688388,2025-04-11,16.30,17.28,17.57,16.22,133395,2.291449e+08,8.37,7.13,1.15,3.13
1388,嘉元科技,688388,2025-04-14,17.68,18.27,18.35,17.68,94486,1.712168e+08,3.88,5.73,0.99,2.22

In [71]:
o2

,name,code,date,open,close,high,low,volume,amount,amplitude,ratio,changed,turnover
0,嘉元科技,688388,2019-07-22,45.75,39.07,52.17,23.72,402094,2.111280e+09,151.41,107.93,20.28,76.10
1,嘉元科技,688388,2019-07-23,32.17,35.01,37.85,31.46,165822,8.515070e+08,16.36,-10.39,-4.06,31.38
2,嘉元科技,688388,2019-07-24,35.46,38.29,38.58,35.46,179648,9.758346e+08,8.91,9.37,3.28,34.00
3,嘉元科技,688388,2019-07-25,39.20,40.73,43.10,39.19,201243,1.197895e+09,10.21,6.37,2.44,38.09
4,嘉元科技,688388,2019-07-26,41.10,39.80,44.23,39.73,198737,1.216335e+09,11.05,-2.28,-0.93,37.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,嘉元科技,688388,2025-04-08,15.00,15.48,16.24,15.00,111292,1.729183e+08,7.91,-1.28,-0.20,2.61
1385,嘉元科技,688388,2025-04-09,15.30,15.62,15.81,13.50,128757,1.893228e+08,14.92,0.90,0.14,3.02
1386,嘉元科技,688388,2025-04-10,16.48,16.13,17.04,16.08,108232,1.794541e+08,6.15,3.27,0.51,2.54
1387,嘉元科技,688388,2025-04-11,16.30,17.28,17.57,16.22,133395,2.291449e+08,8.37,7.13,1.15,3.13
1388,嘉元科技,688388,2025-04-14,17.68,18.27,18.35,17.68,94486,1.712168e+08,3.88,5.73,0.99,2.22

In [72]:
o24 = o2.query("date >= '2024'").reset_index().copy()
import pandas_ta as ta
o24['e13'] = ta.ema(o24.close, 13)
o24['e21'] = ta.ema(o24.close, 21)
o24['e70'] = ta.ema(o24.close, 70)
o24['e84'] = ta.ema(o24.close, 84)

o24[::-1]

,index,name,code,date,open,close,high,low,volume,amount,amplitude,ratio,changed,turnover,e13,e21,e70,e84
307,1388,嘉元科技,688388,2025-04-14,17.68,18.27,18.35,17.68,94486,171216825.0,3.88,5.73,0.99,2.22,17.651826,17.897686,17.054114,16.724167
306,1387,嘉元科技,688388,2025-04-11,16.30,17.28,17.57,16.22,133395,229144930.0,8.37,7.13,1.15,3.13,17.548797,17.860454,17.018871,16.686918
305,1386,嘉元科技,688388,2025-04-10,16.48,16.13,17.04,16.08,108232,179454094.0,6.15,3.27,0.51,2.54,17.593596,17.918500,17.011302,16.672627
304,1385,嘉元科技,688388,2025-04-09,15.30,15.62,15.81,13.50,128757,189322752.0,14.92,0.90,0.14,3.02,17.837529,18.097350,17.036847,16.685702
303,1384,嘉元科技,688388,2025-04-08,15.00,15.48,16.24,15.00,111292,172918330.0,7.91,-1.28,-0.20,2.61,18.207117,18.345085,17.077915,16.711382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,1085,嘉元科技,688388,2024-01-08,18.76,18.37,19.00,18.36,37208,69320068.0,3.40,-2.34,-0.44,0.90,NaN,NaN,NaN,NaN
3,1084,嘉元科技,688388,2024-01-05,19.18,18.81,19.64,18.69,36011,68783572.0,4.96,-1.72,-0.33,0.87,NaN,NaN,NaN,NaN
2,1083,嘉元科技,688388,2024-01-04,19.54,19.14,19.61,19.07,28451,54737460.0,2.76,-2.05,-0.40,0.69,NaN,NaN,NaN,NaN
1,1082,嘉元科技,688388,2024-01-03,19.61,19.54,19.76,19.40,24198,47357202.0,1.83,-0.61,-0.12,0.59,NaN,NaN,NaN,NaN
0,1081,嘉元科技,688388,2024-01-02,20.28,19.66,20.32,19.65,36287,72055902.0,3.31,-3.01,-0.61,0.88,NaN,NaN,NaN,NaN

In [73]:
o24['golden'] = ta.cross(o24.e13, o24.e70, above=True)
o24[::-1]

,index,name,code,date,open,close,high,low,volume,amount,amplitude,ratio,changed,turnover,e13,e21,e70,e84,golden
307,1388,嘉元科技,688388,2025-04-14,17.68,18.27,18.35,17.68,94486,171216825.0,3.88,5.73,0.99,2.22,17.651826,17.897686,17.054114,16.724167,0
306,1387,嘉元科技,688388,2025-04-11,16.30,17.28,17.57,16.22,133395,229144930.0,8.37,7.13,1.15,3.13,17.548797,17.860454,17.018871,16.686918,0
305,1386,嘉元科技,688388,2025-04-10,16.48,16.13,17.04,16.08,108232,179454094.0,6.15,3.27,0.51,2.54,17.593596,17.918500,17.011302,16.672627,0
304,1385,嘉元科技,688388,2025-04-09,15.30,15.62,15.81,13.50,128757,189322752.0,14.92,0.90,0.14,3.02,17.837529,18.097350,17.036847,16.685702,0
303,1384,嘉元科技,688388,2025-04-08,15.00,15.48,16.24,15.00,111292,172918330.0,7.91,-1.28,-0.20,2.61,18.207117,18.345085,17.077915,16.711382,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,1085,嘉元科技,688388,2024-01-08,18.76,18.37,19.00,18.36,37208,69320068.0,3.40,-2.34,-0.44,0.90,NaN,NaN,NaN,NaN,0
3,1084,嘉元科技,688388,2024-01-05,19.18,18.81,19.64,18.69,36011,68783572.0,4.96,-1.72,-0.33,0.87,NaN,NaN,NaN,NaN,0
2,1083,嘉元科技,688388,2024-01-04,19.54,19.14,19.61,19.07,28451,54737460.0,2.76,-2.05,-0.40,0.69,NaN,NaN,NaN,NaN,0
1,1082,嘉元科技,688388,2024-01-03,19.61,19.54,19.76,19.40,24198,47357202.0,1.83,-0.61,-0.12,0.59,NaN,NaN,NaN,NaN,0
0,1081,嘉元科技,688388,2024-01-02,20.28,19.66,20.32,19.65,36287,72055902.0,3.31,-3.01,-0.61,0.88,NaN,NaN,NaN,NaN,0

,index,name,code,date,open,close,high,low,volume,amount,amplitude,ratio,changed,turnover,e13,e21,e70,e84,golden
0,1081,嘉元科技,688388,2024-01-02,20.28,19.66,20.32,19.65,36287,72055902.0,3.31,-3.01,-0.61,0.88,NaN,NaN,NaN,NaN,0
1,1082,嘉元科技,688388,2024-01-03,19.61,19.54,19.76,19.40,24198,47357202.0,1.83,-0.61,-0.12,0.59,NaN,NaN,NaN,NaN,0
2,1083,嘉元科技,688388,2024-01-04,19.54,19.14,19.61,19.07,28451,54737460.0,2.76,-2.05,-0.40,0.69,NaN,NaN,NaN,NaN,0
3,1084,嘉元科技,688388,2024-01-05,19.18,18.81,19.64,18.69,36011,68783572.0,4.96,-1.72,-0.33,0.87,NaN,NaN,NaN,NaN,0
4,1085,嘉元科技,688388,2024-01-08,18.76,18.37,19.00,18.36,37208,69320068.0,3.40,-2.34,-0.44,0.90,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,1384,嘉元科技,688388,2025-04-08,15.00,15.48,16.24,15.00,111292,172918330.0,7.91,-1.28,-0.20,2.61,18.207117,18.345085,17.077915,16.711382,0
304,1385,嘉元科技,688388,2025-04-09,15.30,15.62,15.81,13.50,128757,189322752.0,14.92,0.90,0.14,3.02,17.837529,18.097350,17.036847,16.685702,0
305,1386,嘉元科技,688388,2025-04-10,16.48,16.13,17.04,16.08,108232,179454094.0,6.15,3.27,0.51,2.54,17.593596,17.918500,17.011302,16.672627,0
306,1387,嘉元科技,688388,2025-04-11,16.30,17.28,17.57,16.22,133395,229144930.0,8.37,7.13,1.15,3.13,17.548797,17.860454,17.018871,16.686918,0
307,1388,嘉元科技,688388,2025-04-14,17.68,18.27,18.35,17.68,94486,171216825.0,3.88,5.73,0.99,2.22,17.651826,17.897686,17.054114,16.724167,0